name: ForestCore
version: '${project.version}'
main: ru.forestcore.ForestCore
api-version: '1.16'
authors: [camper_crafting]
description: Core plugin for Forest plugins
commands:
  fcore:
    description: Main command for ForestCore
    usage: /fcore [help|reload|info] [plugin-id]
    aliases: [forestcore] 